### ISSUE TITLE
Does not work on R 3.1.x

### ISSUE THREAD

**Issue by gaborcsardi** [sjp/selectr#8] opened 2018-03-07 22:37 UTC
I am not sure how important this is for you. Would you consider a PR?

```r
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] selectr_0.3-2

loaded via a namespace (and not attached):
[1] stringr_0.6.2 tools_3.1.3
>        css_to_xpath(".testclass")
Error in (function (class_selector)  : could not find function "xpath"
>        css_to_xpath("#testid", prefix = "")
Error in (function (id_selector)  : could not find function "xpath"
>        css_to_xpath("#testid .testclass")
Error in (function (combined)  : could not find function "usingMethods"
>        css_to_xpath(":checked", translator = "html")
Error in (function (pseudo)  : could not find function "usingMethods"
```

**Comment by sjp** [comment] 2018-03-08 00:37
Hi.

Yes, I'll take a PR. I've had difficulties with reference class methods not being visible at certain times (#7). `usingMethods()` being missing is a bit concerning.

Do you have steps to reproduce this?

**Comment by sjp** [comment] 2018-03-08 01:51
Thanks -- I can reproduce with that.

Still a bit strange that methods and fields are (sometimes?) having visibility issues.

**Comment by gaborcsardi** [comment] 2018-03-14 09:53
@sjp Would you be interested in a PR that rewrites the package using R6 classes?

**Comment by sjp** [comment] 2018-03-14 12:21
I think if the solution is to use something other than Reference Classes
I'm inclined to rewrite to S3, mostly to avoid pulling in extra
dependencies.

I'll work on the rewrite sometime this week. If it doesn't work out nicely
I'll gladly try switching to R6.

For now hold off on working on the PR.

**Comment by gaborcsardi** [comment] 2018-03-14 12:27
Sounds good. 

I guess the question is whether you need reference semantics or not. If you don't then yes, S3 is a good way to go. If you do, then R6 is the best alternative I think.

**Comment by sjp** [comment] 2018-03-14 14:11
Yeah, I don't particularly need it. I only really used Reference Classes
initially to most closely match Python's OO system for easy porting.

At the time R6 didn't exist and would probably be my preferred option if I
were to do the same thing now.

**Comment by sjp** [comment] 2018-03-17 22:14
@gaborcsardi I believe this is now fixed as of c08dc9c.

I've checked this via the 3.1 docker image. Are you able to confirm by pulling the latest code from the master branch?

**Comment by sjp** [comment] 2018-03-22 22:08
I'll be closing this because I think this is fixed now after the switch to `R6`.

If you continue to encounter issues with the code in the master branch, feel free to re-open this issue.

**Closed by sjp** 2018-03-22 22:08 UTC

**Comment by gaborcsardi** [comment] 2018-04-03 23:08
Thanks much! Looking forward  to using this! Any plans for CRAN submission?

**Comment by gaborcsardi** [comment] 2018-04-03 23:27
Wow, great! Thanks much!
